/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.99
 * Generated at: 2024-03-07 16:44:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class calcular_005fareas_005ffigura_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html=\"pt-br\">\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("		<title> CÃ¡lculo de Ãreas</title>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("	</head>\r\n");
      out.write("	<body>\r\n");
      out.write("       ");

            int intFiguraGeometrica;
            String strTituloFormulario, strFormulario;

            if(request.getParameter("TipoFigura") !=  null)
                intFiguraGeometrica = Integer.parseInt(request.getParameter("TipoFigura"));
            else 
                intFiguraGeometrica = 0;

            if(intFiguraGeometrica == 1){
                strTituloFormulario = "Calculo da area de um Retangulo";
                strFormulario = "<form name='formCalculoAreasFiguras' method='get' action='area_retangulo.jsp'>";
            }else if(intFiguraGeometrica == 2){
                strTituloFormulario = "Calculo da area de uma Circunferencia";
                strFormulario = "<form name='formCalculoAreasFiguras' method='get' action='area_circunferencia.jsp'>";
            }else if(intFiguraGeometrica == 3){
                strTituloFormulario = "Calculo da area de um Triangulo";
                strFormulario = "<form name='formCalculoAreasFiguras' method='get' action='area_triangulo.jsp'>";
            }else{
                strTituloFormulario ="**Erro**";
                strFormulario = "<form name='formCalculoAreasFiguras'>" ;
            }
            out.println(strFormulario);
       
      out.write("\r\n");
      out.write("       <h2 style=\"text-align: center;\"> ");
      out.print( strTituloFormulario  );
      out.write("</h2>\r\n");
      out.write("        \r\n");
      out.write("       ");

            if((intFiguraGeometrica == 1)||(intFiguraGeometrica == 3)){
                out.println("<p> Digite o valor da altura:");
                out.println("<input name='fldAltura' type='text' size='8' maxlength='8'/>");
                out.println("</p>");

                out.println("<p> Digite o valor da largura:");
                out.println("<input name='fldLargura' type='text' size='8' maxlength='8'/>");
                out.println("</p>");
            }else if(intFiguraGeometrica == 2){
                out.println("<p> Digite o valor o raio da circunferencia:");
                out.println("<input name='fldRaio' type='text' size='8' maxlength='8'/>");
                out.println("</p>");
            }else{
                out.println("<h2>Deve ser especificado o tipo de figura</h2>");
            }
       
      out.write("\r\n");
      out.write("       <p>\r\n");
      out.write("            <input type=\"submit\" name=\"btnCalcular\" value=\"Calcular\"/>\r\n");
      out.write("       </p>    \r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
