# Generated by Django 5.0.3 on 2024-03-20 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banho',
            fields=[
                ('banid', models.AutoField(primary_key=True, serialize=False)),
                ('banvalor', models.FloatField()),
                ('bandatahora', models.DateTimeField()),
            ],
            options={
                'db_table': 'banho',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Formapagamento',
            fields=[
                ('fpgid', models.AutoField(primary_key=True, serialize=False)),
                ('fpgdescricao', models.CharField(blank=True, max_length=65, null=True)),
            ],
            options={
                'db_table': 'formapagamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ong',
            fields=[
                ('ongid', models.AutoField(primary_key=True, serialize=False)),
                ('ongnome', models.CharField(max_length=65)),
                ('ongcidade', models.CharField(blank=True, max_length=70, null=True)),
                ('ongbairro', models.CharField(max_length=70)),
                ('ongrua', models.CharField(max_length=70)),
                ('ongnum', models.SmallIntegerField()),
                ('ongtelefone', models.CharField(blank=True, max_length=15, null=True)),
                ('ongemail', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ong',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('pesid', models.AutoField(primary_key=True, serialize=False)),
                ('pescpf', models.CharField(max_length=11)),
                ('pesdtnascto', models.DateField()),
                ('pessexo', models.CharField(max_length=1)),
                ('pescidade', models.CharField(max_length=65)),
                ('pesbairro', models.CharField(max_length=65)),
                ('pesrua', models.CharField(max_length=65)),
                ('pesemail', models.CharField(max_length=65)),
                ('pesnumero', models.SmallIntegerField()),
                ('pestelefone', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'pessoa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('petid', models.AutoField(primary_key=True, serialize=False)),
                ('petnome', models.CharField(max_length=65)),
                ('petsexo', models.CharField(max_length=1)),
                ('petcastrado', models.CharField(max_length=12)),
                ('petdtnascto', models.DateField()),
                ('petpeso', models.FloatField()),
            ],
            options={
                'db_table': 'pet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PetFoto',
            fields=[
                ('pftid', models.AutoField(primary_key=True, serialize=False)),
                ('pftfoto', models.ImageField(upload_to='adocao/images/pet')),
            ],
            options={
                'db_table': 'pet_foto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PetPorte',
            fields=[
                ('ptpid', models.AutoField(primary_key=True, serialize=False)),
                ('ptpnome', models.CharField(max_length=65)),
                ('ptpdescricao', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pet_porte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PetRaca',
            fields=[
                ('ptrid', models.AutoField(primary_key=True, serialize=False)),
                ('ptrnome', models.CharField(blank=True, max_length=65, null=True)),
            ],
            options={
                'db_table': 'pet_raca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Petshop',
            fields=[
                ('ptsid', models.AutoField(primary_key=True, serialize=False)),
                ('ptsnome', models.CharField(blank=True, max_length=65, null=True)),
                ('ptscnpj', models.CharField(max_length=20)),
                ('ptscidade', models.CharField(blank=True, max_length=65, null=True)),
                ('ptsbairro', models.CharField(blank=True, max_length=65, null=True)),
                ('ptsrua', models.CharField(blank=True, max_length=65, null=True)),
                ('ptsnumero', models.SmallIntegerField(blank=True, null=True)),
                ('ptstelefone', models.CharField(blank=True, max_length=15, null=True)),
                ('ptsemail', models.CharField(blank=True, max_length=65, null=True)),
            ],
            options={
                'db_table': 'petshop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PetTipo',
            fields=[
                ('pttid', models.AutoField(primary_key=True, serialize=False)),
                ('pttnome', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'pet_tipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('proid', models.AutoField(primary_key=True, serialize=False)),
                ('pronome', models.CharField(blank=True, max_length=65, null=True)),
                ('propreco', models.FloatField(blank=True, null=True)),
                ('prosaldo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'produto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProdutoFoto',
            fields=[
                ('prfid', models.AutoField(primary_key=True, serialize=False)),
                ('prffoto', models.ImageField(upload_to='adocao/images/produto')),
            ],
            options={
                'db_table': 'produto_foto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tosa',
            fields=[
                ('tosid', models.AutoField(primary_key=True, serialize=False)),
                ('tosvalor', models.FloatField()),
                ('tosdatahora', models.DateTimeField()),
            ],
            options={
                'db_table': 'tosa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('venid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'venda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PetAdocao',
            fields=[
                ('pet_petid', models.OneToOneField(db_column='pet_petid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='adocao.pet')),
            ],
            options={
                'db_table': 'pet_adocao',
                'managed': False,
            },
        ),
    ]
