# Generated by Django 5.0.3 on 2024-03-28 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itemvenda',
            fields=[
                ('produto_proid', models.OneToOneField(db_column='produto_proid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='adocao.produto')),
                ('itvqtde', models.IntegerField()),
            ],
            options={
                'db_table': 'itemvenda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('serid', models.AutoField(primary_key=True, serialize=False)),
                ('servalor', models.FloatField()),
                ('tosdatahora', models.DateTimeField()),
            ],
            options={
                'db_table': 'servico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiposervico',
            fields=[
                ('tpsid', models.AutoField(primary_key=True, serialize=False)),
                ('tpsnome', models.CharField(max_length=70)),
                ('tpsdescricao', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tiposervico',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Banho',
        ),
        migrations.DeleteModel(
            name='Tosa',
        ),
    ]
