# Generated by Django 2.1.15 on 2024-03-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0002_pet_petfoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdocaoPet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'adocao_pet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdocaoPetteste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'adocao_petteste',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ong',
            fields=[
                ('ongid', models.IntegerField(primary_key=True, serialize=False)),
                ('ongnome', models.CharField(max_length=65)),
                ('ongcidade', models.CharField(blank=True, max_length=70, null=True)),
                ('ongbairro', models.CharField(max_length=70)),
                ('ongrua', models.CharField(max_length=70)),
                ('ongnum', models.SmallIntegerField()),
                ('ongcep', models.CharField(blank=True, max_length=15, null=True)),
                ('ongtelefone', models.CharField(blank=True, max_length=15, null=True)),
                ('ongemail', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ong',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('pesid', models.IntegerField(primary_key=True, serialize=False)),
                ('pescpf', models.CharField(max_length=11)),
                ('pesdtnascto', models.DateField()),
                ('pessexo', models.CharField(max_length=1)),
                ('pescidade', models.CharField(max_length=65)),
                ('pesbairro', models.CharField(max_length=65)),
                ('pesrua', models.CharField(max_length=65)),
                ('pesemail', models.CharField(max_length=65)),
                ('pesnumero', models.SmallIntegerField()),
                ('pestelefone', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'pessoa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PetPorte',
            fields=[
                ('ptpid', models.IntegerField(primary_key=True, serialize=False)),
                ('ptpnome', models.CharField(max_length=65)),
                ('ptpdescricao', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pet_porte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PetRaca',
            fields=[
                ('ptrid', models.IntegerField(primary_key=True, serialize=False)),
                ('ptrnome', models.CharField(blank=True, max_length=65, null=True)),
            ],
            options={
                'db_table': 'pet_raca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PetTipo',
            fields=[
                ('pttid', models.IntegerField(primary_key=True, serialize=False)),
                ('pttnome', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'pet_tipo',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='petteste',
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='petfoto',
            options={'managed': False},
        ),
    ]
