# Generated by Django 5.0.3 on 2024-03-15 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0003_auto_20240312_1244'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pet',
            table='pet',
        ),
        migrations.AlterModelTable(
            name='petfoto',
            table='pet_foto',
        ),
    ]
