# Generated by Django 5.0.3 on 2024-08-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0005_alter_avaliacao_options_alter_carrinho_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('ctpid', models.AutoField(primary_key=True, serialize=False)),
                ('ctpnome', models.CharField(max_length=60)),
                ('ctpdescricao', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'categoria_produto',
                'managed': False,
            },
        ),
    ]
