# Generated by Django 5.0.3 on 2024-03-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='foto',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
